name: horas_complementares
description: "Aplicativo para controle de horas complementares do Centro Universitário da Católica de Santa Catarina"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 8.0.0
  go_router: 14.6.0
  dio: 5.7.0
  melos: 6.2.0
  shared_preferences: 2.3.3
  full_coverage: 1.0.0
  firebase_auth: 5.3.3
  connectivity_plus: 6.1.0
  in_app_purchase: 3.2.0
  flutter_secure_storage: 9.2.2
  firebase_remote_config: 5.1.5
  firebase_core: 3.8.0
  file_picker: 8.1.5
  path_provider: 2.1.5
  open_file: 3.5.10

  design_system:
    path: ./packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutterando_analysis: 0.0.2
  change_app_package_name: 1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
